on:
  push:
    tags:
      - v*

name: Build image

jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup env var
        run: |
          echo "VERSION=${GITHUB_REF_NAME/v/}" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          cache-from: |
            type=gha,mode=max
          cache-to: |
            type=gha
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          platforms: |
            linux/amd64
